controller_frequency:       5.0
recovery_behaviour_enabled: true

#NavfnROS:
#  allow_unknown:            true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
#  default_tolerance:        0.1 # A tolerance on the goal point for the planner.


#Global Planner Parametres

BaseGlobalPlanner:
 allow_unknown: true #false
 use_dijkstra: false #Use A* instead
 use_quadratic: false
 use_grid_path: false
 old_navfn_behavior: false


