#Move_base Parametres
controller_frequency:       5.0
planner_frequency: 1.0
oscillation_distance: 0.2
planner_patience: 3
controller_patience: 3
conservative_reset_dist: 0.5
recovery_behaviour_enabled: true

#Global Planner Parametres

BaseGlobalPlanner:
 allow_unknown: true #false
 use_dijkstra: true #Use A* instead
 use_quadratic: true
 use_grid_path: false
 old_navfn_behavior: false
 lethal_cost: 255
 neutral_cost: 66
 cost_factor: 0.55
 


#Local planner
TebLocalPlannerROS:
  xy_goal_tolerance: 0.7
  yaw_goal_tolerance: 1.5
  weight_kinematics_forward_drive: 1000.0
