controller_frequency:       5.0
recovery_behaviour_enabled: true

#Global Planner Parametres

BaseGlobalPlanner:
 allow_unknown: true #false
 use_dijkstra: false #Use A* instead
 use_quadratic: false
 use_grid_path: false
 old_navfn_behavior: false

EBandPlannerROS:
  xy_goal_tolerance: 0.02 #Default 0.02 , 0.5
  yaw_goal_tolerance: 6.28 #Default 1.5 . We do not care for orientation at the moment
  Ctrl_Rate: 10.0 #30
  disallow_hysteresis: true
  max_vel_lin: 0.75 #default:0.75 ,1.5

#TebLocalPlannerROS:
