#Move_base Parametres
controller_frequency:       5.0
planner_frequency: 1.0
oscillation_distance: 0.2
planner_patience: 3
controller_patience: 3
conservative_reset_dist: 0.5
recovery_behaviour_enabled: true

#Global Planner Parametres

BaseGlobalPlanner:
 allow_unknown: true #false
 use_dijkstra: true #Use A* instead
 use_quadratic: true
 use_grid_path: false
 old_navfn_behavior: false
 lethal_cost: 255
 neutral_cost: 66
 cost_factor: 0.55
 


#Local planner
TebLocalPlannerROS:
  inflation_dist: 0.3
  dt_ref: 1.0 #default 0.3
  dt_hysterisis: 0.5 #default 0.1
  no_outer_iterations: 5
  global_plan_viapoint_sep: 1.0
  exact_arc_length: true
  dt_hysteresis: 0.2 
  max_vel_x: 1.0
  max_vel_theta: 1.0 
  obstacle_poses_affected: 15
  xy_goal_tolerance: 0.7
  yaw_goal_tolerance: 1.5
  acc_lim_theta: 0.31
  acc_lim_x: 0.31
  max_vel_x_backwards: 0.5
  penalty_epsilon: 0.3 #has to be lower than acc_lim_theta,acc_lim_x,max_vel_x_backwards
  weight_kinematics_forward_drive: 50.0


